// <auto-generated />
using System;
using ERPApplication.InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPApplication.InfrastructureLayer.Migrations
{
    [DbContext(typeof(ERPDataContext))]
    partial class ERPDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cycle")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("LeaveAmmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("LeaveCycleStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmountOfLeavePerCycle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Leave");

                    b.HasDiscriminator<int>("LeaveTypeId");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateProcessed")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveStatusId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.LeaveStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentHead")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentHead")
                        .IsUnique()
                        .HasFilter("[DepartmentHead] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportingManagerId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeStatusId");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex("UnitId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.EmployeeOTP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.EmployeeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleOwner")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleOwner");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitHead")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UnitHead");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.AllocatedTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAllocated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TicketId");

                    b.ToTable("AllocatedTicket");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("SupportTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TicketStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SupportTypeId");

                    b.HasIndex("TicketStatusId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.TicketAttachedFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckSum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketAttachedFiles");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.TicketSupportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SupportTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketSupportTypes");
                });

            modelBuilder.Entity("EmployeeeRoleBridge", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("EmployeeeRoleBridge");
                });

            modelBuilder.Entity("TicketSupportTypeUnitBridge", b =>
                {
                    b.Property<int>("TicketSupportTypesId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsId")
                        .HasColumnType("int");

                    b.HasKey("TicketSupportTypesId", "UnitsId");

                    b.HasIndex("UnitsId");

                    b.ToTable("TicketSupportTypeUnitBridge");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.AnnualLeave", b =>
                {
                    b.HasBaseType("ERPApplication.DomainLayer.Models.Leave.Leave");

                    b.Property<double>("LeaveCarriedOver")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.FamilyResponsibilityLeave", b =>
                {
                    b.HasBaseType("ERPApplication.DomainLayer.Models.Leave.Leave");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.SickLeave", b =>
                {
                    b.HasBaseType("ERPApplication.DomainLayer.Models.Leave.Leave");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.UnpaidLeave", b =>
                {
                    b.HasBaseType("ERPApplication.DomainLayer.Models.Leave.Leave");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.Leave", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Leave.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Leave.LeaveRequest", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Leave.LeaveStatus", "LeaveStatus")
                        .WithMany()
                        .HasForeignKey("LeaveStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Leave.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Department", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("ERPApplication.DomainLayer.Models.Organisation.Department", "DepartmentHead")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Employee", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.EmployeeStatus", "EmployeeStatus")
                        .WithMany()
                        .HasForeignKey("EmployeeStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", null)
                        .WithMany()
                        .HasForeignKey("ReportingManagerId");

                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.EmployeeOTP", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("ERPApplication.DomainLayer.Models.Organisation.EmployeeOTP", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Role", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", "Owner")
                        .WithMany()
                        .HasForeignKey("RoleOwner")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Organisation.Unit", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", null)
                        .WithMany()
                        .HasForeignKey("UnitHead")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.AllocatedTicket", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Tickets.Ticket", "Ticket")
                        .WithMany("AllocatedTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Tickets.TicketSupportType", "SupportType")
                        .WithMany()
                        .HasForeignKey("SupportTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Tickets.TicketStatus", "TicketStatus")
                        .WithMany()
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SupportType");

                    b.Navigation("TicketStatus");
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.TicketAttachedFiles", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Tickets.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeeRoleBridge", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketSupportTypeUnitBridge", b =>
                {
                    b.HasOne("ERPApplication.DomainLayer.Models.Tickets.TicketSupportType", null)
                        .WithMany()
                        .HasForeignKey("TicketSupportTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPApplication.DomainLayer.Models.Organisation.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPApplication.DomainLayer.Models.Tickets.Ticket", b =>
                {
                    b.Navigation("AllocatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
